// MODEL STATUS: PRE-RELEASE
// The on-device accident-detection model is under development and training.
// This file is a PLACEHOLDER trained on synthetic data solely to validate the
// inference pipeline. It has not been validated on real crash data and must not
// be used for real-world safety decisions. Replace it with the validated model.
// Generated by tools/train_placeholder_model.py - do not edit by hand.



    // !!! This file is generated using emlearn !!!

    #include <stdint.h>
    

static inline int32_t event_model_tree_0(const float *features, int32_t features_length) {
          if (features[6] < 12.689301f) {
              if (features[5] < 14.955962f) {
                  if (features[1] < 1.008999f) {
                      if (features[7] < 5.969084f) {
                          if (features[1] < 1.005674f) {
                              if (features[0] < 1.182799f) {
                                  if (features[3] < 24.530972f) {
                                      return 0;
                                  } else {
                                      return 0;
                                  }
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[9] < 10.529862f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[8] < 19.745778f) {
                          return 0;
                      } else {
                          if (features[1] < 1.015176f) {
                              if (features[2] < 0.045952f) {
                                  if (features[8] < 76.781200f) {
                                      return 1;
                                  } else {
                                      return 1;
                                  }
                              } else {
                                  if (features[3] < 44.456047f) {
                                      return 1;
                                  } else {
                                      return 0;
                                  }
                              }
                          } else {
                              if (features[0] < 1.518767f) {
                                  if (features[4] < 0.114547f) {
                                      return 1;
                                  } else {
                                      return 1;
                                  }
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[7] < 6.183300f) {
                      if (features[9] < 4.567510f) {
                          if (features[2] < 0.454834f) {
                              if (features[5] < 89.748310f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              return 2;
                          }
                      } else {
                          if (features[6] < 6.943213f) {
                              return 1;
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      if (features[0] < 1.934367f) {
                          return 0;
                      } else {
                          if (features[7] < 8.766502f) {
                              if (features[1] < 1.176044f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          } else {
              if (features[2] < 0.184520f) {
                  return 0;
              } else {
                  if (features[7] < 0.427966f) {
                      return 2;
                  } else {
                      if (features[5] < 83.314137f) {
                          return 0;
                      } else {
                          return 2;
                      }
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_1(const float *features, int32_t features_length) {
          if (features[6] < 11.911939f) {
              if (features[9] < 4.176938f) {
                  if (features[3] < 542.269989f) {
                      if (features[7] < 11.430306f) {
                          if (features[5] < 76.802700f) {
                              return 0;
                          } else {
                              if (features[5] < 77.639229f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          return 2;
                      }
                  } else {
                      if (features[1] < 1.096349f) {
                          return 0;
                      } else {
                          return 2;
                      }
                  }
              } else {
                  if (features[5] < 30.998078f) {
                      return 1;
                  } else {
                      return 2;
                  }
              }
          } else {
              if (features[5] < 70.764145f) {
                  return 0;
              } else {
                  if (features[7] < 0.676884f) {
                      return 2;
                  } else {
                      return 2;
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_2(const float *features, int32_t features_length) {
          if (features[5] < 77.552273f) {
              if (features[9] < 4.199788f) {
                  if (features[3] < 550.101837f) {
                      if (features[0] < 3.015613f) {
                          if (features[5] < 65.826302f) {
                              return 0;
                          } else {
                              if (features[1] < 1.028710f) {
                                  if (features[4] < 0.164526f) {
                                      return 0;
                                  } else {
                                      return 0;
                                  }
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[3] < 428.572708f) {
                              if (features[3] < 423.912048f) {
                                  if (features[6] < 9.030750f) {
                                      return 0;
                                  } else {
                                      return 0;
                                  }
                              } else {
                                  return 0;
                              }
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[5] < 61.125473f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              } else {
                  if (features[0] < 2.186465f) {
                      return 1;
                  } else {
                      return 2;
                  }
              }
          } else {
              if (features[0] < 2.391976f) {
                  if (features[6] < 10.014724f) {
                      return 0;
                  } else {
                      return 2;
                  }
              } else {
                  if (features[6] < 7.938588f) {
                      return 0;
                  } else {
                      if (features[3] < 293.654404f) {
                          return 2;
                      } else {
                          if (features[3] < 398.148254f) {
                              if (features[0] < 2.935267f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_3(const float *features, int32_t features_length) {
          if (features[3] < 520.894745f) {
              if (features[3] < 56.194151f) {
                  if (features[9] < 5.550691f) {
                      return 0;
                  } else {
                      return 1;
                  }
              } else {
                  if (features[7] < 5.533277f) {
                      if (features[9] < 4.958802f) {
                          if (features[2] < 0.361111f) {
                              if (features[5] < 76.459866f) {
                                  return 0;
                              } else {
                                  if (features[2] < 0.260956f) {
                                      return 0;
                                  } else {
                                      return 0;
                                  }
                              }
                          } else {
                              if (features[5] < 71.124725f) {
                                  return 0;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[2] < 0.169356f) {
                              return 1;
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      if (features[0] < 2.536785f) {
                          if (features[5] < 56.325346f) {
                              return 0;
                          } else {
                              return 2;
                          }
                      } else {
                          return 2;
                      }
                  }
              }
          } else {
              if (features[5] < 51.295115f) {
                  return 0;
              } else {
                  if (features[5] < 60.849472f) {
                      return 2;
                  } else {
                      return 2;
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_4(const float *features, int32_t features_length) {
          if (features[3] < 516.774445f) {
              if (features[9] < 3.644383f) {
                  if (features[2] < 0.411159f) {
                      if (features[6] < 13.483005f) {
                          if (features[5] < 90.646431f) {
                              if (features[7] < 9.280819f) {
                                  return 0;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      } else {
                          if (features[0] < 2.384511f) {
                              return 0;
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      return 2;
                  }
              } else {
                  if (features[6] < 7.001295f) {
                      if (features[3] < 63.714825f) {
                          return 1;
                      } else {
                          return 1;
                      }
                  } else {
                      return 2;
                  }
              }
          } else {
              if (features[2] < 0.373945f) {
                  if (features[7] < 2.226056f) {
                      if (features[2] < 0.315849f) {
                          return 0;
                      } else {
                          return 0;
                      }
                  } else {
                      return 2;
                  }
              } else {
                  if (features[2] < 0.418988f) {
                      if (features[2] < 0.414427f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  } else {
                      return 2;
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_5(const float *features, int32_t features_length) {
          if (features[5] < 70.201977f) {
              if (features[8] < 25.032350f) {
                  if (features[0] < 3.641665f) {
                      if (features[7] < 6.589906f) {
                          return 0;
                      } else {
                          return 2;
                      }
                  } else {
                      if (features[7] < 6.884739f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              } else {
                  if (features[5] < 16.728337f) {
                      if (features[9] < 5.542292f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[7] < 6.083862f) {
                          if (features[9] < 10.455269f) {
                              return 0;
                          } else {
                              return 2;
                          }
                      } else {
                          if (features[0] < 2.785922f) {
                              return 0;
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          } else {
              if (features[7] < 2.444341f) {
                  if (features[3] < 514.552490f) {
                      if (features[5] < 103.243656f) {
                          return 0;
                      } else {
                          return 2;
                      }
                  } else {
                      return 2;
                  }
              } else {
                  if (features[5] < 75.547112f) {
                      if (features[6] < 8.736243f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  } else {
                      return 2;
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_6(const float *features, int32_t features_length) {
          if (features[7] < 4.018552f) {
              if (features[8] < 25.040236f) {
                  if (features[3] < 545.323181f) {
                      if (features[1] < 1.061392f) {
                          return 0;
                      } else {
                          if (features[2] < 0.316328f) {
                              return 0;
                          } else {
                              if (features[4] < 0.425228f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[5] < 122.654968f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              } else {
                  if (features[6] < 5.867387f) {
                      if (features[3] < 56.358198f) {
                          if (features[5] < 14.160005f) {
                              if (features[1] < 1.008914f) {
                                  if (features[5] < 2.227188f) {
                                      return 1;
                                  } else {
                                      return 0;
                                  }
                              } else {
                                  if (features[3] < 32.329176f) {
                                      return 1;
                                  } else {
                                      return 1;
                                  }
                              }
                          } else {
                              if (features[9] < 7.092313f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[5] < 5.875012f) {
                              return 1;
                          } else {
                              if (features[9] < 2.981785f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[9] < 5.623930f) {
                          return 0;
                      } else {
                          if (features[5] < 40.657657f) {
                              return 1;
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          } else {
              if (features[1] < 1.052098f) {
                  if (features[0] < 1.885891f) {
                      if (features[9] < 5.605938f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[2] < 0.177075f) {
                          return 2;
                      } else {
                          if (features[5] < 49.244715f) {
                              return 2;
                          } else {
                              return 2;
                          }
                      }
                  }
              } else {
                  if (features[5] < 25.948953f) {
                      return 1;
                  } else {
                      if (features[5] < 46.871023f) {
                          return 0;
                      } else {
                          if (features[6] < 9.822392f) {
                              if (features[2] < 0.393866f) {
                                  return 0;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[7] < 5.408098f) {
                                  if (features[7] < 5.308078f) {
                                      return 2;
                                  } else {
                                      return 2;
                                  }
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_7(const float *features, int32_t features_length) {
          if (features[2] < 0.363445f) {
              if (features[8] < 25.826324f) {
                  if (features[7] < 6.173846f) {
                      if (features[9] < 5.628234f) {
                          if (features[6] < 13.321792f) {
                              if (features[3] < 397.028610f) {
                                  return 0;
                              } else {
                                  if (features[0] < 3.023572f) {
                                      return 0;
                                  } else {
                                      return 0;
                                  }
                              }
                          } else {
                              return 0;
                          }
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[7] < 7.401770f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              } else {
                  if (features[3] < 55.387419f) {
                      if (features[4] < 0.127169f) {
                          if (features[9] < 5.613493f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[1] < 1.020051f) {
                              if (features[0] < 1.302220f) {
                                  if (features[9] < 6.154221f) {
                                      return 0;
                                  } else {
                                      return 1;
                                  }
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[9] < 5.521705f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[5] < 87.064251f) {
                          if (features[0] < 1.416894f) {
                              if (features[4] < 0.226634f) {
                                  if (features[9] < 2.732595f) {
                                      return 0;
                                  } else {
                                      return 0;
                                  }
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 526.881897f) {
                                  if (features[7] < 12.909083f) {
                                      return 0;
                                  } else {
                                      return 2;
                                  }
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[5] < 108.136600f) {
                              if (features[7] < 2.822794f) {
                                  return 0;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          } else {
              if (features[2] < 0.420700f) {
                  if (features[1] < 1.094086f) {
                      if (features[0] < 3.715988f) {
                          if (features[3] < 494.636887f) {
                              return 2;
                          } else {
                              if (features[6] < 10.590708f) {
                                  return 0;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[7] < 8.846992f) {
                              return 2;
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      return 0;
                  }
              } else {
                  if (features[0] < 3.597146f) {
                      return 2;
                  } else {
                      if (features[7] < 0.733100f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_8(const float *features, int32_t features_length) {
          if (features[5] < 70.201977f) {
              if (features[5] < 15.110475f) {
                  if (features[9] < 5.530305f) {
                      return 0;
                  } else {
                      return 1;
                  }
              } else {
                  if (features[7] < 6.600760f) {
                      if (features[9] < 6.016278f) {
                          if (features[2] < 0.442844f) {
                              return 0;
                          } else {
                              return 2;
                          }
                      } else {
                          if (features[5] < 33.063760f) {
                              return 1;
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      if (features[3] < 339.372345f) {
                          return 0;
                      } else {
                          return 2;
                      }
                  }
              }
          } else {
              if (features[4] < 0.300033f) {
                  if (features[9] < 3.766636f) {
                      if (features[9] < 0.033412f) {
                          if (features[6] < 10.571117f) {
                              return 0;
                          } else {
                              return 2;
                          }
                      } else {
                          return 0;
                      }
                  } else {
                      return 2;
                  }
              } else {
                  if (features[7] < 0.600691f) {
                      return 2;
                  } else {
                      if (features[6] < 7.906025f) {
                          return 0;
                      } else {
                          if (features[0] < 3.512419f) {
                              if (features[1] < 1.080410f) {
                                  if (features[6] < 12.451997f) {
                                      return 0;
                                  } else {
                                      return 2;
                                  }
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t event_model_tree_9(const float *features, int32_t features_length) {
          if (features[2] < 0.363445f) {
              if (features[5] < 14.955729f) {
                  if (features[4] < 0.119949f) {
                      if (features[9] < 5.646066f) {
                          return 0;
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[0] < 1.169735f) {
                          if (features[9] < 5.541478f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[9] < 5.429183f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      }
                  }
              } else {
                  if (features[6] < 13.483005f) {
                      if (features[9] < 5.368916f) {
                          if (features[3] < 546.020020f) {
                              if (features[0] < 2.215985f) {
                                  return 0;
                              } else {
                                  if (features[6] < 12.685817f) {
                                      return 0;
                                  } else {
                                      return 2;
                                  }
                              }
                          } else {
                              return 2;
                          }
                      } else {
                          if (features[0] < 1.698930f) {
                              return 1;
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      if (features[3] < 261.427521f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              }
          } else {
              if (features[3] < 549.222107f) {
                  if (features[6] < 11.321540f) {
                      if (features[0] < 3.400576f) {
                          return 2;
                      } else {
                          if (features[7] < 2.521082f) {
                              return 0;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[1] < 1.096157f) {
                          return 2;
                      } else {
                          return 2;
                      }
                  }
              } else {
                  if (features[7] < 0.643796f) {
                      return 2;
                  } else {
                      return 2;
                  }
              }
          }
        }
        

int32_t event_model_predict(const float *features, int32_t features_length) {

        int32_t votes[3] = {0,};
        int32_t _class = -1;

        _class = event_model_tree_0(features, features_length); votes[_class] += 1;
    _class = event_model_tree_1(features, features_length); votes[_class] += 1;
    _class = event_model_tree_2(features, features_length); votes[_class] += 1;
    _class = event_model_tree_3(features, features_length); votes[_class] += 1;
    _class = event_model_tree_4(features, features_length); votes[_class] += 1;
    _class = event_model_tree_5(features, features_length); votes[_class] += 1;
    _class = event_model_tree_6(features, features_length); votes[_class] += 1;
    _class = event_model_tree_7(features, features_length); votes[_class] += 1;
    _class = event_model_tree_8(features, features_length); votes[_class] += 1;
    _class = event_model_tree_9(features, features_length); votes[_class] += 1;
    
        int32_t most_voted_class = -1;
        int32_t most_voted_votes = 0;
        for (int32_t i=0; i<3; i++) {

            if (votes[i] > most_voted_votes) {
                most_voted_class = i;
                most_voted_votes = votes[i];
            }
        }
        return most_voted_class;
    }
    

int event_model_predict_proba(const float *features, int32_t features_length, float *out, int out_length) {

        int32_t _class = -1;

        for (int i=0; i<out_length; i++) {
            out[i] = 0.0f;
        }

        _class = event_model_tree_0(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_1(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_2(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_3(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_4(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_5(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_6(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_7(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_8(features, features_length); out[_class] += 1.0f;
    _class = event_model_tree_9(features, features_length); out[_class] += 1.0f;
    
        // compute mean
        for (int i=0; i<out_length; i++) {
            out[i] = out[i] / 10;
        }
        return 0;
    }
    