// MODEL STATUS: PRE-RELEASE
// The on-device accident-detection model is under development and training.
// This file is a PLACEHOLDER trained on synthetic data solely to validate the
// inference pipeline. It has not been validated on real crash data and must not
// be used for real-world safety decisions. Replace it with the validated model.
// Generated by tools/train_placeholder_model.py - do not edit by hand.



    // !!! This file is generated using emlearn !!!

    #include <stdint.h>
    

static inline int32_t severity_model_tree_0(const float *features, int32_t features_length) {
          if (features[4] < 0.856451f) {
              if (features[0] < 5.825070f) {
                  if (features[8] < 51.199184f) {
                      if (features[6] < 42.428526f) {
                          if (features[8] < 40.246372f) {
                              if (features[0] < 5.482811f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[2] < 0.416470f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          return 0;
                      }
                  } else {
                      if (features[9] < 44.243984f) {
                          if (features[0] < 4.266975f) {
                              if (features[1] < 1.042235f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[2] < 0.489753f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[7] < 59.492537f) {
                              if (features[0] < 3.158110f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 0;
                          }
                      }
                  }
              } else {
                  if (features[8] < 29.870385f) {
                      if (features[3] < 1228.010864f) {
                          if (features[8] < 16.474258f) {
                              if (features[0] < 6.671967f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[2] < 0.597050f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[6] < 40.426191f) {
                              if (features[6] < 21.563627f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[5] < 454.411026f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[5] < 80.382900f) {
                          return 1;
                      } else {
                          if (features[8] < 45.870371f) {
                              if (features[2] < 0.668945f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[7] < 9.036758f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              }
          } else {
              if (features[0] < 12.058003f) {
                  if (features[9] < 38.349848f) {
                      if (features[0] < 7.397384f) {
                          if (features[9] < 19.816039f) {
                              if (features[9] < 2.409179f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[0] < 5.715799f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[3] < 1968.837463f) {
                              if (features[6] < 10.874949f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 2175.990723f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[9] < 49.435049f) {
                          if (features[2] < 0.948391f) {
                              return 1;
                          } else {
                              if (features[3] < 1791.923950f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[3] < 1554.917297f) {
                              if (features[8] < 66.760242f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[1] < 1.186257f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              } else {
                  if (features[8] < 5.029344f) {
                      return 2;
                  } else {
                      if (features[9] < 21.123981f) {
                          if (features[3] < 2572.552124f) {
                              if (features[5] < 222.740036f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[4] < 1.397760f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[9] < 31.351037f) {
                              if (features[3] < 2284.095581f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[1] < 1.336118f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_1(const float *features, int32_t features_length) {
          if (features[9] < 36.210579f) {
              if (features[0] < 6.861288f) {
                  if (features[3] < 924.683136f) {
                      if (features[9] < 27.862071f) {
                          if (features[5] < 112.389042f) {
                              if (features[5] < 103.204159f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[0] < 4.303428f) {
                              if (features[5] < 318.630722f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[5] < 326.025162f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[7] < 7.663526f) {
                          if (features[1] < 1.131471f) {
                              return 0;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[6] < 8.350381f) {
                              return 1;
                          } else {
                              if (features[8] < 25.063643f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[2] < 1.648514f) {
                      if (features[2] < 1.197608f) {
                          if (features[5] < 85.744671f) {
                              if (features[9] < 22.743260f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[8] < 11.058619f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[3] < 2226.839355f) {
                              if (features[9] < 14.134835f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[0] < 13.296252f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  } else {
                      if (features[9] < 1.120487f) {
                          if (features[0] < 11.417368f) {
                              if (features[7] < 40.233398f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[5] < 497.173401f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[6] < 58.872723f) {
                              if (features[6] < 14.932621f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[1] < 1.476670f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          } else {
              if (features[2] < 1.097220f) {
                  if (features[4] < 0.840320f) {
                      if (features[1] < 1.063557f) {
                          if (features[2] < 0.336638f) {
                              if (features[8] < 78.405262f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[7] < 29.087410f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[0] < 3.994690f) {
                              if (features[7] < 29.397161f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 1381.587708f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[1] < 1.202217f) {
                          if (features[3] < 1483.398865f) {
                              if (features[2] < 0.949557f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 1778.159668f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[8] < 77.681393f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  }
              } else {
                  if (features[3] < 1986.018982f) {
                      if (features[9] < 44.520887f) {
                          if (features[4] < 1.717164f) {
                              if (features[6] < 32.091291f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 1;
                          }
                      } else {
                          if (features[0] < 8.609883f) {
                              return 1;
                          } else {
                              if (features[6] < 17.202917f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  } else {
                      if (features[6] < 58.821424f) {
                          return 2;
                      } else {
                          if (features[3] < 2132.046631f) {
                              return 2;
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_2(const float *features, int32_t features_length) {
          if (features[1] < 1.164741f) {
              if (features[0] < 5.825070f) {
                  if (features[9] < 40.221601f) {
                      if (features[2] < 0.637139f) {
                          if (features[5] < 377.568909f) {
                              if (features[2] < 0.458309f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[9] < 28.807322f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[9] < 21.178726f) {
                              return 0;
                          } else {
                              if (features[5] < 361.815399f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[3] < 554.375366f) {
                          if (features[0] < 3.088712f) {
                              if (features[8] < 81.254818f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[1] < 1.085884f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[7] < 47.812963f) {
                              return 1;
                          } else {
                              if (features[9] < 50.739578f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[3] < 1230.789429f) {
                      if (features[9] < 26.250896f) {
                          if (features[9] < 13.651089f) {
                              if (features[2] < 0.586508f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[3] < 1034.023743f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[4] < 0.484780f) {
                              return 1;
                          } else {
                              return 1;
                          }
                      }
                  } else {
                      if (features[9] < 54.823683f) {
                          if (features[4] < 0.761376f) {
                              if (features[8] < 29.909141f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[5] < 258.450096f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          return 1;
                      }
                  }
              }
          } else {
              if (features[0] < 12.219323f) {
                  if (features[3] < 1360.763367f) {
                      if (features[3] < 1092.930054f) {
                          if (features[8] < 33.523891f) {
                              return 0;
                          } else {
                              if (features[5] < 300.249908f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[8] < 32.413815f) {
                              if (features[8] < 12.918729f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[3] < 1156.027222f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[9] < 51.732891f) {
                          if (features[0] < 11.068610f) {
                              if (features[3] < 1955.298828f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 2158.648193f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[3] < 1496.252441f) {
                              return 1;
                          } else {
                              if (features[9] < 53.674116f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              } else {
                  if (features[3] < 2444.874634f) {
                      if (features[3] < 2436.418335f) {
                          if (features[3] < 2253.532593f) {
                              if (features[3] < 2246.978516f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[9] < 1.828305f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          return 1;
                      }
                  } else {
                      if (features[2] < 1.800412f) {
                          if (features[4] < 1.309414f) {
                              if (features[9] < 3.858315f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[1] < 1.279777f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[3] < 2786.784790f) {
                              if (features[9] < 1.120487f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_3(const float *features, int32_t features_length) {
          if (features[0] < 6.843829f) {
              if (features[3] < 822.214111f) {
                  if (features[9] < 41.691341f) {
                      if (features[5] < 377.752106f) {
                          if (features[9] < 38.028517f) {
                              if (features[2] < 0.620491f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[0] < 3.447030f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[4] < 0.605133f) {
                              if (features[1] < 1.081035f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[1] < 1.060681f) {
                          if (features[0] < 3.283025f) {
                              if (features[4] < 0.257979f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[8] < 74.283878f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[7] < 41.532095f) {
                              if (features[4] < 0.554111f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[1] < 1.096474f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  }
              } else {
                  if (features[8] < 44.573034f) {
                      if (features[9] < 16.373760f) {
                          if (features[7] < 41.174843f) {
                              if (features[0] < 6.724302f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[0] < 6.328678f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[5] < 295.229797f) {
                              if (features[9] < 19.672021f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[8] < 37.917688f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[1] < 1.139564f) {
                          if (features[1] < 1.112890f) {
                              if (features[9] < 24.319504f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[0] < 5.832667f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[6] < 43.012728f) {
                              if (features[0] < 6.655049f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          } else {
              if (features[8] < 74.171501f) {
                  if (features[9] < 35.403734f) {
                      if (features[9] < 1.120487f) {
                          if (features[0] < 11.090456f) {
                              if (features[3] < 1807.130005f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[0] < 12.027827f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[0] < 12.268602f) {
                              if (features[9] < 12.259280f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[8] < 20.536975f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  } else {
                      if (features[0] < 9.925686f) {
                          if (features[7] < 8.593514f) {
                              if (features[3] < 1552.781372f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[5] < 336.937820f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[4] < 1.041184f) {
                              if (features[2] < 1.042333f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[0] < 10.701561f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              } else {
                  if (features[9] < 39.672194f) {
                      if (features[0] < 13.192315f) {
                          if (features[3] < 1263.154114f) {
                              return 1;
                          } else {
                              if (features[2] < 1.351968f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          return 2;
                      }
                  } else {
                      if (features[0] < 8.018155f) {
                          return 1;
                      } else {
                          if (features[9] < 46.433304f) {
                              if (features[2] < 1.609572f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[2] < 1.335374f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_4(const float *features, int32_t features_length) {
          if (features[3] < 1132.391724f) {
              if (features[9] < 27.620210f) {
                  if (features[0] < 5.915641f) {
                      if (features[4] < 0.865839f) {
                          if (features[2] < 0.656878f) {
                              if (features[8] < 44.505980f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[4] < 0.760187f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[6] < 25.623307f) {
                              return 0;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[3] < 1000.820770f) {
                          return 1;
                      } else {
                          if (features[8] < 21.356992f) {
                              if (features[7] < 25.371250f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[5] < 317.070633f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[9] < 42.431942f) {
                      if (features[3] < 650.511047f) {
                          if (features[1] < 1.084170f) {
                              if (features[9] < 40.429045f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[7] < 26.584161f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[4] < 0.565786f) {
                              if (features[1] < 1.082225f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[0] < 5.154700f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[3] < 564.403137f) {
                          if (features[5] < 236.563385f) {
                              if (features[8] < 74.120975f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[9] < 57.543228f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[5] < 403.078445f) {
                              if (features[7] < 46.174295f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          } else {
              if (features[0] < 11.118994f) {
                  if (features[0] < 7.397384f) {
                      if (features[4] < 0.921078f) {
                          if (features[9] < 24.048656f) {
                              if (features[9] < 2.764557f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[5] < 309.337372f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[8] < 34.125120f) {
                              if (features[9] < 2.550095f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[1] < 1.218745f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[3] < 1650.283997f) {
                          if (features[8] < 70.402489f) {
                              if (features[0] < 8.798401f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 1394.273132f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[6] < 47.248575f) {
                              if (features[9] < 48.792114f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[7] < 34.224386f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[3] < 2221.980103f) {
                      if (features[9] < 36.424059f) {
                          if (features[0] < 11.877101f) {
                              if (features[7] < 23.213892f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[3] < 2173.795410f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[8] < 65.147095f) {
                              if (features[0] < 11.713689f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      }
                  } else {
                      if (features[8] < 5.029344f) {
                          return 2;
                      } else {
                          if (features[9] < 21.123981f) {
                              if (features[5] < 639.431305f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[8] < 50.581427f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_5(const float *features, int32_t features_length) {
          if (features[1] < 1.155413f) {
              if (features[8] < 52.946678f) {
                  if (features[3] < 1123.037292f) {
                      if (features[8] < 21.356992f) {
                          if (features[1] < 1.141010f) {
                              if (features[3] < 1032.990906f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[7] < 32.975620f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[3] < 895.517181f) {
                              if (features[9] < 42.421585f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[1] < 1.145045f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[0] < 8.480237f) {
                          if (features[9] < 1.713068f) {
                              if (features[7] < 23.911891f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[5] < 369.924042f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[6] < 20.508554f) {
                              return 1;
                          } else {
                              if (features[4] < 0.753896f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[9] < 44.436028f) {
                      if (features[3] < 642.589325f) {
                          if (features[9] < 40.429045f) {
                              return 0;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[2] < 0.480225f) {
                              if (features[1] < 1.064318f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[9] < 18.542961f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[2] < 0.247440f) {
                          return 1;
                      } else {
                          if (features[0] < 7.884102f) {
                              if (features[0] < 4.051279f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 1;
                          }
                      }
                  }
              }
          } else {
              if (features[9] < 36.329752f) {
                  if (features[0] < 12.225784f) {
                      if (features[0] < 7.397384f) {
                          if (features[0] < 6.844718f) {
                              if (features[9] < 15.710798f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[4] < 0.901026f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[9] < 2.624413f) {
                              if (features[3] < 1968.837463f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[3] < 1599.403809f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[7] < 9.935905f) {
                          if (features[4] < 2.000064f) {
                              if (features[9] < 2.107880f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[0] < 13.937684f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[4] < 2.237672f) {
                              if (features[0] < 12.769443f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[7] < 21.310238f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              } else {
                  if (features[3] < 1666.186768f) {
                      if (features[4] < 1.559576f) {
                          if (features[3] < 1475.277405f) {
                              if (features[2] < 0.964272f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[8] < 68.155827f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          return 2;
                      }
                  } else {
                      if (features[2] < 1.712908f) {
                          if (features[3] < 1986.893494f) {
                              if (features[9] < 42.609085f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      } else {
                          if (features[9] < 37.120163f) {
                              return 2;
                          } else {
                              if (features[8] < 59.480373f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_6(const float *features, int32_t features_length) {
          if (features[4] < 0.843747f) {
              if (features[8] < 44.079884f) {
                  if (features[3] < 1125.072449f) {
                      if (features[9] < 29.787595f) {
                          if (features[3] < 913.765137f) {
                              return 0;
                          } else {
                              if (features[4] < 0.689186f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[2] < 0.336034f) {
                              return 0;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[6] < 39.881786f) {
                          if (features[3] < 1224.030579f) {
                              if (features[5] < 238.148582f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[2] < 0.742081f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[3] < 1453.766846f) {
                              if (features[8] < 6.015867f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          } else {
                              return 1;
                          }
                      }
                  }
              } else {
                  if (features[3] < 785.796051f) {
                      if (features[2] < 0.247946f) {
                          if (features[9] < 45.009214f) {
                              return 0;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[9] < 42.908804f) {
                              if (features[6] < 41.542456f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[7] < 56.050531f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[8] < 87.706551f) {
                          if (features[9] < 15.856689f) {
                              return 0;
                          } else {
                              if (features[9] < 24.267440f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          return 1;
                      }
                  }
              }
          } else {
              if (features[0] < 12.065813f) {
                  if (features[8] < 50.740795f) {
                      if (features[9] < 17.620907f) {
                          if (features[1] < 1.235124f) {
                              if (features[2] < 0.843670f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[4] < 1.485303f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[9] < 26.703999f) {
                              if (features[2] < 0.909707f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[8] < 32.683924f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  } else {
                      if (features[1] < 1.292455f) {
                          if (features[3] < 1934.160278f) {
                              if (features[0] < 8.740726f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[2] < 1.091024f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[3] < 2005.089844f) {
                              if (features[9] < 50.835573f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[5] < 414.822830f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              } else {
                  if (features[3] < 2444.874634f) {
                      if (features[9] < 1.661058f) {
                          return 2;
                      } else {
                          if (features[8] < 45.052698f) {
                              if (features[8] < 29.219399f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[3] < 2301.806274f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  } else {
                      if (features[5] < 314.884094f) {
                          if (features[2] < 2.181076f) {
                              if (features[9] < 26.785890f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[0] < 14.353688f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[8] < 5.125289f) {
                              return 2;
                          } else {
                              if (features[8] < 28.318408f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              }
          }
        }
        

static inline int32_t severity_model_tree_7(const float *features, int32_t features_length) {
          if (features[2] < 0.743727f) {
              if (features[8] < 49.913300f) {
                  if (features[0] < 6.473663f) {
                      if (features[9] < 31.669347f) {
                          if (features[2] < 0.516475f) {
                              if (features[3] < 848.513489f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[0] < 5.779325f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          }
                      } else {
                          if (features[1] < 1.079053f) {
                              return 0;
                          } else {
                              if (features[2] < 0.505581f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[8] < 6.926895f) {
                          if (features[3] < 1258.621155f) {
                              if (features[4] < 0.565661f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[5] < 234.095261f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[6] < 13.337130f) {
                              return 0;
                          } else {
                              if (features[6] < 34.326958f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  }
              } else {
                  if (features[9] < 32.803371f) {
                      if (features[4] < 0.628968f) {
                          if (features[3] < 879.316895f) {
                              if (features[6] < 37.537035f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[3] < 812.010040f) {
                              return 0;
                          } else {
                              return 1;
                          }
                      }
                  } else {
                      if (features[0] < 4.220127f) {
                          if (features[9] < 50.499125f) {
                              if (features[0] < 3.799669f) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[2] < 0.249160f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[5] < 310.508881f) {
                              return 1;
                          } else {
                              if (features[5] < 353.243530f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      }
                  }
              }
          } else {
              if (features[3] < 2010.921631f) {
                  if (features[1] < 1.232085f) {
                      if (features[0] < 7.406760f) {
                          if (features[7] < 1.373209f) {
                              return 0;
                          } else {
                              if (features[9] < 19.344007f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[0] < 10.685714f) {
                              if (features[8] < 84.981094f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[7] < 47.525738f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  } else {
                      if (features[7] < 8.681602f) {
                          if (features[3] < 1625.130493f) {
                              if (features[3] < 1498.648376f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[0] < 10.634123f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          }
                      } else {
                          if (features[8] < 61.616762f) {
                              if (features[9] < 40.194988f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          } else {
                              if (features[9] < 49.144114f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  }
              } else {
                  if (features[9] < 35.403734f) {
                      if (features[9] < 1.638888f) {
                          if (features[2] < 1.187733f) {
                              if (features[2] < 1.112276f) {
                                  return 2;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[2] < 1.710146f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          }
                      } else {
                          if (features[3] < 2619.197388f) {
                              if (features[0] < 12.840332f) {
                                  return 1;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[9] < 11.092744f) {
                                  return 1;
                              } else {
                                  return 2;
                              }
                          }
                      }
                  } else {
                      if (features[3] < 2226.188843f) {
                          if (features[1] < 1.428257f) {
                              if (features[9] < 36.697451f) {
                                  return 2;
                              } else {
                                  return 2;
                              }
                          } else {
                              return 2;
                          }
                      } else {
                          return 2;
                      }
                  }
              }
          }
        }
        

int32_t severity_model_predict(const float *features, int32_t features_length) {

        int32_t votes[3] = {0,};
        int32_t _class = -1;

        _class = severity_model_tree_0(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_1(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_2(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_3(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_4(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_5(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_6(features, features_length); votes[_class] += 1;
    _class = severity_model_tree_7(features, features_length); votes[_class] += 1;
    
        int32_t most_voted_class = -1;
        int32_t most_voted_votes = 0;
        for (int32_t i=0; i<3; i++) {

            if (votes[i] > most_voted_votes) {
                most_voted_class = i;
                most_voted_votes = votes[i];
            }
        }
        return most_voted_class;
    }
    

int severity_model_predict_proba(const float *features, int32_t features_length, float *out, int out_length) {

        int32_t _class = -1;

        for (int i=0; i<out_length; i++) {
            out[i] = 0.0f;
        }

        _class = severity_model_tree_0(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_1(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_2(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_3(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_4(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_5(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_6(features, features_length); out[_class] += 1.0f;
    _class = severity_model_tree_7(features, features_length); out[_class] += 1.0f;
    
        // compute mean
        for (int i=0; i<out_length; i++) {
            out[i] = out[i] / 8;
        }
        return 0;
    }
    