#!/usr/bin/env python3
"""
Train the PLACEHOLDER two-stage accident model and export it as C headers.

MODEL STATUS: PRE-RELEASE. The validated accident-detection model is still under
development and training. This script builds a stand-in trained on SYNTHETIC
impact windows so the on-device pipeline (sampling -> features -> model ->
severity -> uplink) can be exercised end to end. The synthetic labels encode the
generator's assumptions, not real crash data: results on the synthetic test set
say nothing about real-world accuracy.

To integrate the real model: train your own sklearn RandomForest pair on the same
10 features (see `features()` below / feature_extract.cpp), then export with
`export_model()` into model_event.h and model_severity.h.

Usage:  pip install numpy scikit-learn emlearn
        python3 train_placeholder_model.py
Outputs: ../segura_esp32/model_event.h, ../segura_esp32/model_severity.h,
         host_test/parity_windows.csv (used by the C++ host test)
"""
import os
import numpy as np
import emlearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

FS, N = 200, 100                      # sample rate, window length (config.h)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "segura_esp32")
NAMES = ["peak_g", "mean_g", "std_g", "peak_jerk_gps", "impulse_ms",
         "peak_gyro_dps", "mean_gyro_dps", "tilt_change_deg",
         "speed_kmh", "speed_drop_kmh"]

BANNER = """// MODEL STATUS: PRE-RELEASE
// The on-device accident-detection model is under development and training.
// This file is a PLACEHOLDER trained on synthetic data solely to validate the
// inference pipeline. It has not been validated on real crash data and must not
// be used for real-world safety decisions. Replace it with the validated model.
// Generated by tools/train_placeholder_model.py - do not edit by hand.
"""

# ------------------------------------------------------------------ features
def features(w, speed, drop):
    """Must mirror feature_extract.cpp exactly. w: (N,6) = ax,ay,az [g], gx,gy,gz [deg/s]."""
    a, g = w[:, :3].astype(np.float64), w[:, 3:].astype(np.float64)
    mag = np.linalg.norm(a, axis=1)
    gm = np.linalg.norm(g, axis=1)
    k = min(10, len(w) // 4)
    v0, v1 = a[:k].sum(0), a[-k:].sum(0)
    n0, n1 = np.linalg.norm(v0), np.linalg.norm(v1)
    tilt = 0.0
    if n0 > 1e-6 and n1 > 1e-6:
        tilt = np.degrees(np.arccos(np.clip(v0 @ v1 / (n0 * n1), -1, 1)))
    return np.array([
        mag.max(), mag.mean(), mag.std(),
        np.abs(np.diff(mag)).max() * FS,
        np.maximum(mag - 1, 0).sum() / FS * 9.81,
        gm.max(), gm.mean(), tilt,
        speed, max(drop, 0.0)], dtype=np.float64)

# ------------------------------------------------- synthetic window generator
def unit(rng, horizontal_bias=False):
    v = rng.normal(size=3)
    if horizontal_bias: v[2] *= 0.4
    return v / np.linalg.norm(v)

def gravity(rng, sigma_deg=4.0):
    r, p = np.radians(rng.normal(0, sigma_deg, 2))
    return np.array([-np.sin(p), np.sin(r) * np.cos(p), np.cos(r) * np.cos(p)])

def rotate(v, axis, deg):
    t = np.radians(deg)
    return v * np.cos(t) + np.cross(axis, v) * np.sin(t) + axis * (axis @ v) * (1 - np.cos(t))

def base(rng):
    g = gravity(rng)
    acc = g + rng.normal(0, rng.uniform(0.01, 0.06), (N, 3))
    gyr = rng.normal(0, rng.uniform(0.5, 4.0), (N, 3))
    return acc, gyr, g

def finish(acc, gyr):
    return np.hstack([np.clip(acc, -16, 16), np.clip(gyr, -1000, 1000)])

def gen_normal(rng):
    acc, gyr, _ = base(rng)
    for _ in range(rng.integers(0, 4)):                     # road bumps
        i, wd = rng.integers(0, N - 9), rng.integers(3, 9)
        acc[i:i + wd, 2] += rng.uniform(0.15, 1.1) * np.sin(np.linspace(0, np.pi, wd))
        gyr[i:i + wd] += rng.normal(0, 15, (wd, 3))
    if rng.random() < 0.4:                                  # cornering
        s, L = rng.integers(0, 60), rng.integers(20, 40)
        amp = rng.uniform(0.1, 0.5) * rng.choice([-1, 1])
        acc[s:s + L, 1] += amp * np.hanning(L)
        gyr[s:s + L, 2] += rng.uniform(5, 40) * np.sign(amp) * np.hanning(L)
    if rng.random() < 0.15:                                 # pothole spike, no ringing/rotation
        i = rng.integers(0, N - 2)
        acc[i:i + rng.integers(1, 3), 2] += rng.uniform(1.0, 2.6)
        gyr[i] += rng.normal(0, 25, 3)
    speed = rng.uniform(0, 90) if rng.random() < 0.75 else 0.0
    return finish(acc, gyr), speed, (rng.uniform(0, 3) if speed > 0 else 0.0)

def gen_hard_brake(rng):
    acc, gyr, _ = base(rng)
    s = rng.integers(0, 55); L = rng.integers(20, 45)
    idx = np.arange(L)
    env = np.clip(np.minimum(idx / 5, (L - 1 - idx) / 5), 0, 1)
    acc[s:s + L, 0] -= rng.uniform(0.35, 0.95) * env
    speed = rng.uniform(25, 90)
    return finish(acc, gyr), speed, rng.uniform(8, min(speed, 60))

def gen_crash(rng):
    acc, gyr, g = base(rng)
    i, A, wdt = rng.integers(8, N - 12), rng.uniform(2.5, 15.0), rng.integers(1, 4)
    d = unit(rng, horizontal_bias=True)
    acc[i:i + wdt] += A * d
    k = np.arange(N - i - wdt)
    ring = A * 0.35 * np.exp(-k / 7) * np.cos(2 * np.pi * k / rng.uniform(4, 9))
    acc[i + wdt:] += ring[:, None] * d
    gyr[i:] += (rng.uniform(80, 700) * (0.4 + 0.6 * A / 15)) * unit(rng) * \
               np.exp(-np.arange(N - i) / 10)[:, None]
    g2 = rotate(g, unit(rng), rng.uniform(0, 70))           # vehicle ends up rotated
    acc[i + wdt:] += g2 - g
    if rng.random() < 0.3: speed, drop = 0.0, 0.0           # e.g. no GPS fix
    else:
        speed = rng.uniform(10, 90); drop = speed * rng.uniform(0.2, 1.0)
    score = (A - 2.5) / 12.5 if speed == 0 else 0.6 * (A - 2.5) / 12.5 + 0.4 * min(drop / 60, 1)
    score += rng.normal(0, 0.05)
    sev = 0 if score < 0.34 else (1 if score < 0.67 else 2)  # minor / moderate / severe
    return finish(acc, gyr), speed, drop, sev

# ------------------------------------------------------------------- pipeline
def build_dataset(rng, n_windows=12000):
    X, y, sev, raw = [], [], [], []
    for _ in range(n_windows):
        r = rng.random()
        if r < 0.50:   w, sp, dr = gen_normal(rng);     cls, sv = 0, -1
        elif r < 0.70: w, sp, dr = gen_hard_brake(rng); cls, sv = 1, -1
        else:          w, sp, dr, sv = gen_crash(rng);  cls = 2
        X.append(features(w, sp, dr)); y.append(cls); sev.append(sv)
        raw.append((w, sp, dr))
    return np.array(X, np.float32), np.array(y), np.array(sev), raw

def export_model(model, name, path):
    c = emlearn.convert(model, method="inline", dtype="float")
    tmp = path + ".tmp"
    c.save(file=tmp, name=name)
    with open(tmp) as f: body = f.read()
    os.remove(tmp)
    with open(path, "w") as f: f.write(BANNER + body)

def main():
    rng = np.random.default_rng(42)
    X, y, sev, raw = build_dataset(rng)
    Xtr, Xte, ytr, yte, str_, ste = train_test_split(X, y, sev, test_size=0.2, random_state=0, stratify=y)

    m1 = RandomForestClassifier(n_estimators=10, max_depth=7, min_samples_leaf=5, random_state=0).fit(Xtr, ytr)
    print("Stage 1 (normal/hard_brake/crash) - SYNTHETIC hold-out only, not real-world accuracy")
    print(confusion_matrix(yte, m1.predict(Xte)))

    mask_tr, mask_te = ytr == 2, yte == 2
    m2 = RandomForestClassifier(n_estimators=8, max_depth=6, min_samples_leaf=5, random_state=0) \
        .fit(Xtr[mask_tr], str_[mask_tr])
    print("Stage 2 (minor/moderate/severe) - SYNTHETIC hold-out only")
    print(confusion_matrix(ste[mask_te], m2.predict(Xte[mask_te])))

    export_model(m1, "event_model", os.path.join(OUT, "model_event.h"))
    export_model(m2, "severity_model", os.path.join(OUT, "model_severity.h"))
    print("wrote model_event.h, model_severity.h")

    # parity windows for the C++ host test: label,speed,drop,600 raw values,10 python features
    sel = []
    for cls in (0, 1, 2):
        sel += [i for i in range(len(y)) if y[i] == cls][:10]
    with open(os.path.join(HERE, "host_test", "parity_windows.csv"), "w") as f:
        for i in sel:
            w, sp, dr = raw[i]
            vals = [int(y[i]), sp, dr] + list(w.flatten()) + list(features(w, sp, dr))
            f.write(",".join(f"{v:.7g}" for v in vals) + "\n")
    print("wrote host_test/parity_windows.csv")

if __name__ == "__main__":
    main()
